### ISSUE TITLE
conjure-cp image missing in the footer

### ISSUE THREAD

**Issue by ozgurakgun** [conjure-cp/nurse-rostering-demo#33]
![Screenshot 2023-11-12 at 13 49 34](https://github.com/conjure-cp/nurse-rostering-demo/assets/184914/89e51ea3-d2d9-4d44-a1d6-1cf193ba9ff7)

**Comment by YuxinZhang214** [comment]
Sorry, I thought it was a quick fix. I will host the demo on my GitHub page and fix it there.
